

export const homeObjOne = {
    id: 'products',
    lightBg: false,
    lightText: true,
    LightTextDesc: true,
    topLine: 'Investment Services',
    headline: 'Modeling, structuring and data management for projects at all stages',
    description: "From NY to CA, from development loans to tax equity, from small C&I to Utility Scale we've seen it all. ",
    buttonLabel: 'Contact Us',
    listTitleOne: 'Financial Structuring',
    listOneObjectOne: 'Fund Modeling',
    listOneObjectTwo: 'Asset Modeling',
    listOneObjectThree: 'Transaction Negotiation',
    listOneObjectFour: 'Capital Markets Support',
    listOneObjectFive: 'Investor Reporting',
    listTitleTwo: 'Deal Diligence & Data Management',
    listTwoObjectOne: 'Asset Diligence',
    listTwoObjectTwo: 'Project Data Management',
    listTwoObjectThree: 'Regulatory Management',
    listTwoObjectFour: 'Legal & Contract Review',
    listTwoObjectFive: 'Full Technical Stack Diligence',
    imgStart: false,
    img: require('../../images/undraw/undraw_predictive_analytics_green.svg').default,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
    fadeTitleLeft: true,
    fadeTitleRight: false,
    fadeContentLeft: false,
    fadeContentRight: true
};

export const homeObjTwo = {
    id: 'products2',
    lightBg: true,
    lightText: false,
    LightTextDesc: false,
    topLine: 'Energy Storage',
    headline: 'Industry-leading energy storage modeling, risk management, and execution',
    description: 'Get access to our exclusive energy storage revenue, CapEx build-out, OpEx forecasting, and execution tools.',
    buttonLabel: 'Contact Us',
    listTitleOne: 'Technology Diligence',
    listOneObjectOne: 'Vendor & Technology Evaluation',
    listOneObjectTwo: 'Revenue Analysis',
    listOneObjectThree: 'CapEx & OpEx Cost Modeling',
    listOneObjectFour: 'EPC & LTSA Negotiation',
    listOneObjectFive: 'Insurance Budgeting',
    listTitleTwo: 'Engineering & Exection',
    listTwoObjectOne: 'System Desgin',
    listTwoObjectTwo: 'Energy Modeling',
    listTwoObjectThree: 'IE Coordination',
    listTwoObjectFour: 'Onsite Construction Modeling',
    listTwoObjectFive: 'Augmentation Optimization',
    imgStart: true,
    img: require('../../images/undraw/undraw_wind_turbine_green.svg').default,
    alt: 'Car',
    dark: false,
    primary: false,
    darkText: true,
    fadeTitleLeft: false,
    fadeTitleRight: true,
    fadeContentLeft: true,
    fadeContentRight: false
};

export const homeObjThree = {
    id: 'products3',
    lightBg: false,
    lightText: false,
    LightTextDesc: false,
    topLine: 'Execution Services',
    headline: 'On time, on budget, always built right with Euclid',
    description: 'Our project execution excellence, technical know-how, and operational expertise build advantage at every project stage, but shine through during construction. ',
    buttonLabel: 'Contact Us',
    listTitleOne: 'Execution Management',
    listOneObjectOne: 'Contract & Change Management',
    listOneObjectTwo: 'Contractor Supervision',
    listOneObjectThree: 'Supply Chain Coordination',
    listOneObjectFour: 'Milestone Approval',
    listOneObjectFive: 'Commissioning Coordination',
    listTitleTwo: 'Pre-Construction Services',
    listTwoObjectOne: 'Design Services',
    listTwoObjectTwo: 'Equipment Specification',
    listTwoObjectThree: 'Structural / Electrical Oversight',
    listTwoObjectFour: 'Utility and IX management',
    listTwoObjectFive: 'I.E. Coordination & Production',
    imgStart: false,
    img: require('../../images/undraw/undraw_QA_engineers_green.svg').default,
    alt: 'Car',
    dark: false,
    primary: false,
    darkText: true,
    fadeTitleLeft: true,
    fadeTitleRight: false,
    fadeContentLeft: false,
    fadeContentRight: true
};

export const homeObjFour = {
    id: 'products4',
    lightBg: true,
    lightText: false,
    LightTextDesc: false,
    topLine: 'Asset Management',
    headline: "With Euclid, Asset Management isn't an after-thought",
    description: 'Euclid’s multidisciplinary data-driven makes it possible to scale our service offering to comprehensive asset management. At the end of the day, we treat every single asset as our own.',
    buttonLabel: 'Contact Us',
    listTitleOne: 'Operations Support',
    listOneObjectOne: 'O&M Optimization',
    listOneObjectTwo: 'Revenue Optimization',
    listOneObjectThree: 'Data Management & Cleansing',
    listOneObjectFour: 'Critical Spares Review',
    listOneObjectFive: 'Warranty Review & Remedy',
    listTitleTwo: 'Stakeholder Management',
    listTwoObjectOne: 'Powerful Reporting Tools',
    listTwoObjectTwo: 'Incident & Outage Management',
    listTwoObjectThree: 'Retrofit Feasibility Analysis',
    listTwoObjectFour: 'Billing & Collections',
    listTwoObjectFive: 'Customer Contract Negotiation',
    imgStart: true,
    img: require('../../images/undraw/undraw_right_places_green.svg').default,
    alt: 'Car',
    dark: false,
    primary: false,
    darkText: true,
    fadeTitleLeft: false,
    fadeTitleRight: true,
    fadeContentLeft: true,
    fadeContentRight: false
};

export const homeObjFive = {
    id: 'products5',
    lightBg: true,
    lightText: false,
    LightTextDesc: false,
    topLine: 'Execution Services',
    headline: 'On time, on budget, always built right with Euclid',
    description: 'Our project execution excellence, technical know-how, and operational expertise build advantage at every project stage, but shine through during construction. ',
    buttonLabel: 'Contact Us',
    listTitleOne: 'Financial Structuring',
    listOneObjectOne: 'Fund Modeling',
    listOneObjectTwo: 'Asset Modeling',
    listOneObjectThree: 'Transaction Negotiation',
    listOneObjectFour: 'Capital Markets Support',
    listOneObjectFive: 'Investor Reporting',
    listTitleTwo: 'Deal Diligence',
    listTwoObjectOne: 'Asset diligence',
    listTwoObjectTwo: 'Risk identification and mitigation',
    listTwoObjectThree: 'Regulatory Management',
    listTwoObjectFour: 'Legal diligence & contract review',
    listTwoObjectFive: 'Full technical stack diligence',
    imgStart: false,
    img: require('').default,
    alt: 'Car',
    dark: false,
    primary: false,
    darkText: true,
    fadeTitleLeft: true,
    fadeTitleRight: false,
    fadeContentLeft: false,
    fadeContentRight: true
};

