export const careersData1 = {
  SectionOneid: "products",
  SectionOnelightBg: true,
  SectionOnelightText: true,
  SectionOneLightTextDesc: true,
  SectionOnetopLine: "Software",
  SectionOneheadline: "Technical Advisor",
  JDHighLevel:
    "Software advisory for our renewable energy development and investment software platform",
  JDLocation: "Location: Remote",
  JDCommitment: "Part-Time (3-5 hours / week )",
  SectionOnebuttonLabel: "Full Job Description",
  SectionOneimgStart: false,
  SectionOneimg: require("../../images/undraw/undraw_code_typing.svg")
    .default,
  SectionOnealt: "",
  JDHeader1: "Our Story",
  JDSection1:
    "The story of Euclid begins 10 years ago when our co-founder, Ryan Guay, walked into the offices of his first job, at the largest solar installer in New York. The company’s entire 50-project pipeline was written on a whiteboard, with no general plan, tools, or processes in sight to manage the 1,000s of key data points necessary to diligence, build, execute, and finance these complex projects while communicating with dozens of key stakeholders. Over the next decade, Ryan and the rest of the founding team have witnessed firsthand the renewable power industry suffer from cost overruns, massive schedule delays, overlooked project risks, and many, many dead deals from the lack of data and process management. Euclid was founded to bring much-needed operational reprieve to the industry and finally get this process right. As the industry grows, our mission is to capture and track project data so that key players can develop, diligence, build, and finance their projects on time and on budget and, frankly, get more renewable energy deals done.",
  JDHeader2: "About Us",
  JDSection2: [
    "Euclid Power is a renewable energy software and services company that builds data management and workflow tools to help project developers and investors develop, diligence, execute, and asset-manage renewables projects. We believe it is time that the process of deploying renewable energy projects was powered by software, as much as social media or online ads.",
    "Euclid is led by a world-class team of industry-leading veterans with development and investment experience on over 3GW of solar and 1GWh of energy storage projects. We previously created the diligence, investing, and execution process for some of the industry’s leading developers and investors including Goldman Sachs Renewable Power, Blackstone (Onyx), GE Solar, Generate Capital, and True Green Capital. We are seeking a full-stack engineer with proven experience building scalable web apps to join us as a senior advisor and to assist in the architecting and initial buildout of our software toolset.",
    "Our company is committed to hiring talented team-members and advisors who are hardworking, passionate, and committed to our mission. Hires at this stage will immediately contribute to the DNA of our product, processes, and, most importantly, culture. At Euclid, learning, growing, and testing the best ideas are central to our approach to solving one of the world’s most important challenges: climate change.",
  ],
  JDHeader3: "Who You Are",
  JDSection3: [
    "Life-long learner and builder that is passionate about creating great software products to support the deployment of renewable energy projects",
    "Experienced full-stack engineer that can aid in architecting a scalable web-based application",
    "Creative architect that is excited by the opportunity to bring a new product to market that can eventually scale to serve hundreds of customers in the renewables space",
    "Team-player that will collaborate with the founding team to translate (and improve) our proven renewables diligence, execution, and data tools into a proprietary software environment",
    "Leader that can facilitate the review and management of deliverables from an outsourced team of software engineers to build our software MVP",
    "Scrappy, open-minded, entrepreneurial thinker who can guide product decisions in a resource-limited environment and understand the benefits and trade-offs of the many different solutions available for a given problem",
  ],
  JDHeader4: "What You'll Do - Immediate",
  JDSection4: [
    "Aid in development of outreach plan and support evaluation of outsourced engineering team",
    "Support scope definition and resource allocation for outsourced engineering team",
    "Aid founding team in review and management of deliverables from outsourced engineering team that will drive development of product MVP based on the detailed product roadmap Euclid has developed",
    "Work closely with the founding team to learn and understand the process of renewable energy development, diligence, execution, investment, and asset management",
    "2-5 hour time commitment while we build towards web app MVP including calls with founding team, high-level design of web app platform, feedback on dev shop scopes, strategic discussions on software decisions",
  ],
  JDHeader5: "What You'll Do - Long-Term",
  JDSection5: [
"Support hiring and future build-out of internal Euclid frontend and backend software engineering team",
"Develop roadmap for future Euclid software buildout",
"Facilitate design and architecture of new products and tools to serve renewable energy project developers and investors through Euclid’s platform with guidance from the founding members ",
"Work with internal and external engineering resources to incorporate customer feedback into product",
  ],
  JDHeader6: "Required Skills and Experience",
  JDSection6: [
    "5+ years of software development experience",
    "Strong front-end engineering skills with React, Typescript, Javascript",
    "Excellent back-end engineering skills (Python / Django, API, database architecture)",
    "Experience in designing and scaling a REST or GraphQL API",
    "Experience in managing an engineering team or acting in a tech-lead role",
    "Excellent software architecture skills to lay the framework for future scale",
    "Experience in renewables is a plus, but by no means necessary",
  ],
  JDHeader7: "What We Provide",
  JDSection7: [
    "Benefits package (401K, Health Insurance, Remote Work, Paid Time Off, Paid Holidays)",
    "Opportunity for early equity awards and share in the growth of the firm you are helping build ",
    "Professional credential obtainment sponsorship (PMP, PE, CFA, Software)",
    "Multidisciplinary exposure and training (Tax, Legal, Finance, Diligence, Engineering etc.) ",
    "Opportunity to learn and grow in a truly supportive, collaborative, dynamic and diverse environment ",
    "Exposure to high-profile, industry leading clients, products, and technology",
  ],
  JDSection8:
    "We welcome candidates of all races, creeds, genders, and sexuality to apply.",
  JDHeadline: [
    "Location: Remote (With occasional travel to NYC for team or client meetings",
    "Part-Time (3-5 hours / week )",
  ],
};

export const careersData2 = {
  SectionOneid: "products",
  SectionOnelightBg: true,
  SectionOnelightText: true,
  SectionOneLightTextDesc: true,
  SectionOnetopLine: "Execution Services",
  SectionOneheadline: "Program/Portfolio Manager",
  JDHighLevel:
    "Experienced program/project manager looking to lead execution on industry-leading renewable energy projects",
  JDLocation:
    "Location: Remote (With occasional travel to NYC for team or client meetings",
  JDCommitment: "Full-Time (40+ hours / week )",
  SectionOnebuttonLabel: "Full Job Description",
  SectionOneimgStart: false,
  SectionOneimg: require("../../images/undraw/undraw_circles_green.svg")
    .default,
  SectionOnealt: "",
  JDHeader1: "Our Story",
  JDSection1:
    "Euclid Power Inc. execution services group was born out of the founders unwavering commitment to process and ‘doing the right thing.’ We have witnessed firsthand how portfolios in the renewable power industry suffer from cost overruns, massive schedule delays, uninformed stakeholders, overlooked project risks, and many, many dead deals. We were continuously frustrated with the lack of competent technical expertise, data and process management and under-prioritization of deal continuity and organization. Whether it was development and execution on a single 300MW site, or a portfolio of 150kW rooftop projects, overall deal execution always fumbled through the same unstructured and ambiguous process, masked in uncertainty as to where to start and where to head next. Euclid was founded to bring much-needed operational reprieve to the industry and finally get this process right. As the industry grows, our ardent mission is to aid our clients, armed with unmatched technical acumen and industry-specific platform & toolset, in developing, diligencing, building, and financing their projects on time and on budget and, frankly, to ensure more renewable energy deals get done. ",
  JDHeader2: "About Us",
  JDSection2: [
    "Euclid Power is a solar and storage renewable energy services and software company that facilitates the development, diligence, execution, financing, and asset-management of renewables projects in conjunction with renewable energy developers and investors. Euclid provides a transformative data and project management platform, alongside value-add turn-key services, to guide developers and investors through execution on complex projects at all stages of the project lifecycle. Euclid is led by a world-class team of renewable energy veterans with over 3GW of PV and 1GWh of energy storage development, diligence, finance, and execution experience. We have developed the diligence, investing, and execution process for some of the industry’s leading developers and investors, and our results-centered approach focuses on success for our clients no matter the project stage, size, or challenge. We are passionate about renewables, and we work with our clients to get their projects developed, managed, and built right: on time, on budget, and with results that speak for themselves.",
    "We are seeking a Program/Portfolio Manager for our Execution Services Group who is looking to make a sizable impact on the future of the renewable energy industry.",
  ],
  JDHeader3: "Who You Are",
  JDSection3: [
    "A driven self-starter, looking to continue to build on your professional and technical expertise in renewable energy project/portfolio management",
    "Detailed-oriented, organized individual, who fervently believes there is no compromising when it comes to the details",
    "Gritty, with the willingness to roll up your sleeves to support a rapidly growing company by maintaining a “no job is too small” mindset",
    "Clear communicator, with excellent verbal and written communication skills",
    "Team-player, who will collaborate with the founding team to translate (and improve) our proven renewables diligence, execution, and data services offering and toolsets",
    "Scrappy, open-minded, entrepreneurial thinker who can flourish in a resource-limited environment",
    "Customer-focused and personable, with an innate desire to exceed customer expectations",
  ],
  JDHeader4: "What You'll Do - Immediate",
  JDSection4: [
    "Directly oversee multiple, simultaneous high-profile client engagements ranging from market-entry analysis to turn-key project development and execution services in conjunction with the execution team and COO/Co-Founders",
    "Develop master execution plans, including portfolio schedules, budgets, internal/external time tracking, activity costs breakout, and proposal generation",
    "Serve as main Euclid execution services client point of contact and work with clients to execute on execution and engagement plans in coordination with all pertinent stakeholders",
    "Support overall company and project specific functions in collaboration with the COO/Co-Founders including engagement statuses, P&L tracking, and resource loading ",
    "Assist in development and execution of key vendor outreach and engagement plan ",
    "Serve as lead in development of onboarding curriculum by providing training to new project execution team members  ",
    "Work directly with the Euclid founding team on process and execution tool refinement and internal/external infrastructure build out",
  ],
  JDHeader5: "What You'll Do - Long-Term",
  JDSection5: [
    "Advance into an overall leadership role within our execution services group",
    "Oversee multiple project managers and analysts and support team while reporting directly to COO/Co-Founders",
    "Collaborate on the development of strategy for continuous innovation and services offering refinement",
    "Comprehensive analysis of engagement P&L, resource loading and future projections and group growth plan",
    "Serve lead vendor relationship role with key OEMs, technical advisors & firms",
    "Directly influence the design and architecture of new products and tools to serve renewable energy project developers and investors through Euclid’s platform with guidance from the founding members ",
    "Provide integral support in the hiring and future build-out of the Euclid execution services group",
  ],
  JDHeader6: "What You Have",
  JDSection6: [
    "7+ years of proven program, project, construction or operations management experience within the renewable energy, energy, or adjacent industries (preferred) or strong desire to enter the renewables space",
    "Demonstrated experience managing and executing on multiple C&I and/or utility scale PV, PV + storage or standalone storage project",
    "Experience efficiently managing master programs consisting of sub-consultants, vendors, third-party engineering/design firms, EPC contractors etc.",
    "Strong technical acumen and firm grasp of standard equipment, permitting requirements & process, design best practices, standard QA/QC protocols, contracting & negotiation, construction best practices and industry standards (and how to exceed them)",
    "Full knowledge of renewables project lifecycle, inside and outside of project execution, and understanding of key project value drivers, project development and financing",
    "Complete understanding of project and operations management principles and customer success methods and best practices",
    "Bachelor’s or master’s degree in engineering, project/operations/construction management, business management/economics - concentrations preferred, but not required",
    "PE/PMP/PfMP - preferred, but not required",
  ],
  JDHeader7: "What We Provide",
  JDSection7: [
    "Benefits package (401K, Health Insurance, Remote Work, Paid Time Off, Paid Holidays)",
    "Opportunity for early equity awards and share in the growth of the firm you are helping build ",
    "Professional credential obtainment sponsorship (PMP, PE, CFA, Software)",
    "Multidisciplinary exposure and training (Tax, Legal, Finance, Diligence, Engineering etc.) ",
    "Opportunity to learn and grow in a truly supportive, collaborative, dynamic and diverse environment ",
    "Exposure to high-profile, industry leading clients, products, and technology",
  ],
  JDSection8:
    "We welcome candidates of all races, creeds, genders, and sexuality to apply.",
  JDHeadline: [
    "Location: Remote (With occasional travel to NYC for team or client meetings",
    "Part-Time (3-5 hours / week )",
  ],
};

export const careersData3 = {
  SectionOneid: "products",
  SectionOnelightBg: true,
  SectionOnelightText: true,
  SectionOneLightTextDesc: true,
  SectionOnetopLine: "Execution Services",
  SectionOneheadline: "Project Execution Analyst",
  JDHighLevel:
    "Ambitious, early-career opportunity to drive execution on a variety of renewable energy projects",
  JDLocation:
    "Location: Remote (With occasional travel to NYC for team or client meetings",
  JDCommitment: "Full-Time (40+ hours / week )",
  SectionOnebuttonLabel: "Full Job Description",
  SectionOneimgStart: false,
  SectionOneimg: require("../../images/undraw/undraw_circles_green.svg")
    .default,
  SectionOnealt: "",
  JDHeader1: "Our Story",
  JDSection1:
    "Euclid Power Inc. execution services group was born out of the founders unwavering commitment to process and ‘doing the right thing.’ We have witnessed firsthand how portfolios in the renewable power industry suffer from cost overruns, massive schedule delays, uninformed stakeholders, overlooked project risks, and many, many dead deals. We were continuously frustrated with the lack of competent technical expertise, data and process management and under-prioritization of deal continuity and organization. Whether it was development and execution on a single 300MW site, or a portfolio of 150kW rooftop projects, overall deal execution always fumbled through the same unstructured and ambiguous process, masked in uncertainty as to where to start and where to head next. Euclid was founded to bring much-needed operational reprieve to the industry and finally get this process right. As the industry grows, our ardent mission is to aid our clients, armed with unmatched technical acumen and industry-specific platform & toolset, in developing, diligencing, building, and financing their projects on time and on budget and, frankly, to ensure more renewable energy deals get done. ",
  JDHeader2: "About Us",
  JDSection2: [
    "Euclid Power is a solar and storage renewable energy services and software company that facilitates the development, diligence, execution, financing, and asset-management of renewables projects in conjunction with renewable energy developers and investors. Euclid provides a transformative data and project management platform, alongside value-add turn-key services, to guide developers and investors through execution on complex projects at all stages of the project lifecycle. Euclid is led by a world-class team of renewable energy veterans with over 3GW of PV and 1GWh of energy storage development, diligence, finance, and execution experience. We have developed the diligence, investing, and execution process for some of the industry’s leading developers and investors, and our results-centered approach focuses on success for our clients no matter the project stage, size, or challenge. We are passionate about renewables, and we work with our clients to get their projects developed, managed, and built right: on time, on budget, and with results that speak for themselves.",
    "We are seeking a Program/Portfolio Manager for our Execution Services Group who is looking to make a sizable impact on the future of the renewable energy industry.",
  ],
  JDHeader3: "Who You Are",
  JDSection3: [
    "A driven self-starter, looking to continue to build on your professional and technical expertise in renewable energy project/portfolio management",
    "Detailed-oriented, organized individual, who fervently believes there is no compromising when it comes to the details",
    "Gritty, with the willingness to roll up your sleeves to support a rapidly growing company by maintaining a “no job is too small” mindset",
    "Clear communicator, with excellent verbal and written communication skills",
    "Team-player, who will collaborate with the founding team to translate (and improve) our proven renewables diligence, execution, and data services offering and toolsets",
    "Scrappy, open-minded, entrepreneurial thinker who can flourish in a resource-limited environment",
    "Customer-focused and personable, with an innate desire to exceed customer expectations",
  ],
  JDHeader4: "What You'll Do - Immediate",
  JDSection4: [
    "Co-manage and support multiple client engagements under the leadership of an experienced program/project manager or COO",
    "Facilitate vendor on-boarding and general project administration including, but not limited to, document management/ organization and project reporting requirements ",
    "Maintain tools, RFI/submittal trackers, schedules, budgets, meeting minutes, engagement invoicing and support overall company and project-specific functions under direction of the program/project manager or COO ",
    "Work directly with the Euclid founding team on process and execution tool refinement and infrastructure build out",
    "Learn from a world-class, experienced PV and storage development/execution team and work closely with the founding team to learn and understand the process of renewable energy development, diligence, execution, investment, and asset management",
  ],
  JDHeader5: "What You'll Do - Long-Term",
  JDSection5: [
    "Independently manage high-profile clients and frequent exposure to industry distributing technologies",
    "Grow into a Project Manager (and beyond) and overall leader within our execution services group",
    "Support in the design and architecture of new products and tools to serve renewable energy project developers and investors through Euclid’s platform with guidance from the founding members ",
    "Support hiring and future build-out of the Euclid services group",
  ],
  JDHeader6: "What You Have",
  JDSection6: [
"0-3+ years of project or operations management experience in renewable energy, energy, or adjacent industries (preferred) or strong desire to enter the renewables space ",
"Bachelor’s degree in engineering, project/operations/construction management, business management/economics – concentrations preferred, but not required ",
"General knowledge of project management principles and customer success methods and best practices or interest in obtaining further project management certifications",

  ],
  JDHeader7: "What We Provide",
  JDSection7: [
    "Benefits package (401K, Health Insurance, Remote Work, Paid Time Off, Paid Holidays)",
    "Opportunity for early equity awards and share in the growth of the firm you are helping build ",
    "Professional credential obtainment sponsorship (PMP, PE, CFA, Software)",
    "Multidisciplinary exposure and training (Tax, Legal, Finance, Diligence, Engineering etc.) ",
    "Opportunity to learn and grow in a truly supportive, collaborative, dynamic and diverse environment ",
    "Exposure to high-profile, industry leading clients, products, and technology",
  ],
  JDSection8:
    "We welcome candidates of all races, creeds, genders, and sexuality to apply.",
};
