
export const careersData1 = {
  SectionOneid: "products",
  SectionOnelightBg: true,
  SectionOnelightText: true,
  SectionOneLightTextDesc: true,
  SectionOnetopLine: "Software",
  SectionOneheadline:
    "Technical Advisor",
  SectionOnedescription:
    "Software development advisory for our industry-changing renewables data-management and workflow platform.",
  SectionOnebuttonLabel: "Full Job Description",
  SectionOnelistTitleOne: "Financial Structuring & Tax Equity",
  SectionOnelistOneObjectOne: "Fund Modeling",
  SectionOnelistOneObjectTwo: "Asset & Portfolio Modeling",
  SectionOnelistOneObjectThree: "Transaction Negotiation",
  SectionOnelistOneObjectFour: "Capital Markets Support",
  SectionOnelistOneObjectFive: "Investor Reporting",
  SectionOnelistTitleTwo: "Deal Diligence & Data Management",
  SectionOnelistTwoObjectOne: "Asset & Portfolio Diligence",
  SectionOnelistTwoObjectTwo: "Project Data Management",
  SectionOnelistTwoObjectThree: "Regulatory Compliance",
  SectionOnelistTwoObjectFour: "Legal & Contract Review",
  SectionOnelistTwoObjectFive: "Full Technical Stack Diligence",
  SectionOneimgStart: false,
  SectionOneimg: require("../../images/undraw/undraw_dashboard_green.svg")
    .default,
  SectionOnealt: "",
  SectionOnedark: true,
  SectionOneprimary: true,
  SectionOnedarkText: false,
  SectionOnefadeTitleLeft: true,
  SectionOnefadeTitleRight: false,
  SectionOnefadeContentLeft: false,
  SectionOnefadeContentRight: true,
  JDHeader1: "Our Story",
  JDSection1: "The story of Euclid begins 10 years ago when our co-founder, Ryan Guay, walked into the offices of his first job, at the largest solar installer in New York. The company’s entire 50-project pipeline was written on a whiteboard, with no general plan, tools, or processes in sight to manage the 1,000s of key data points necessary to diligence, build, execute, and finance these complex projects while communicating with dozens of key stakeholders. Over the next decade, Ryan and the rest of the founding team have witnessed firsthand the renewable power industry suffer from cost overruns, massive schedule delays, overlooked project risks, and many, many dead deals from the lack of data and process management. Euclid was founded to bring much-needed operational reprieve to the industry and finally get this process right. As the industry grows, our mission is to capture and track project data so that key players can develop, diligence, build, and finance their projects on time and on budget and, frankly, get more renewable energy deals done.",
  JDHeader2: "About Us",
  JDSection2: "Euclid Power is a renewable energy software and services company that builds data management and workflow tools to help project developers and investors develop, diligence, execute, and asset-manage renewables projects. We believe it is time that the process of deploying renewable energy projects was powered by software, as much as social media or online ads. <br> Euclid is led by a world-class team of industry-leading veterans with development and investment experience on over 3GW of solar and 1GWh of energy storage projects. We previously created the diligence, investing, and execution process for some of the industry’s leading developers and investors including Goldman Sachs Renewable Power, Blackstone (Onyx), GE Solar, Generate Capital, and True Green Capital. We are seeking a full-stack engineer with proven experience building scalable web apps to join us as a senior advisor and to assist in the architecting and initial buildout of our software toolset. <br> Our company is committed to hiring talented team-members and advisors who are hardworking, passionate, and committed to our mission. Hires at this stage will immediately contribute to the DNA of our product, processes, and, most importantly, culture. At Euclid, learning, growing, and testing the best ideas are central to our approach to solving one of the world’s most important challenges: climate change.",
  JDHeader3: "Who You Are",
  JDSection3: ["Life-long learner and builder that is passionate about creating great software products to support the deployment of renewable energy projects",
    "Experienced full-stack engineer that can aid in architecting a scalable web-based application",
    "Creative architect that is excited by the opportunity to bring a new product to market that can eventually scale to serve hundreds of customers in the renewables space",
    "Team-player that will collaborate with the founding team to translate (and improve) our proven renewables diligence, execution, and data tools into a proprietary software environment",
    "Leader that can facilitate the review and management of deliverables from an outsourced team of software engineers to build our software MVP",
    "Scrappy, open-minded, entrepreneurial thinker who can guide product decisions in a resource-limited environment and understand the benefits and trade-offs of the many different solutions available for a given problem",
  ],
  JDHeader4: "What You'll Do - Immediate",
  JDSection4: ["Aid in development of outreach plan and support evaluation of outsourced engineering team",
    "Support scope definition and resource allocation for outsourced engineering team",
    "Aid founding team in review and management of deliverables from outsourced engineering team that will drive development of product MVP based on the detailed product roadmap Euclid has developed",
    "Work closely with the founding team to learn and understand the process of renewable energy development, diligence, execution, investment, and asset management",
    "2-5 hour time commitment while we build towards web app MVP including calls with founding team, high-level design of web app platform, feedback on dev shop scopes, strategic discussions on software decisions"],
  JDHeader5: "Required Skills and Experience",
  JDSection5: ["5+ years of software development experience",
    "Strong front-end engineering skills with React, Typescript, Javascript",
    "Excellent back-end engineering skills (Python / Django, API, database architecture)",
    "Experience in designing and scaling a REST or GraphQL API",
    "Experience in managing an engineering team or acting in a tech-lead role",
    "Excellent software architecture skills to lay the framework for future scale",
    "Experience in renewables is a plus, but by no means necessary",
  ],
  JDSection6: "We welcome candidates of all races, creeds, genders, and sexuality to apply."
};