
export const experienceSectionOne = {
    sectionTitle: 'With World Class Experience',
    id: 'experience',
    lightBg: true,
    oneTopLine: 'High Desert Solar and Storage',
    oneHeadline: 'xxMW Solar | xxMWH Storage',
    oneDescription: "",
    oneImg: require('../../images/ProjectImages/BrianJSEdited1.169.jpg').default,
    oneAlt: 'High Desert',
    oneLink: "https://www.energy-storage.news/news/goldman-sachs-renewable-power-buys-california-solar-plus-storage-plant",
    twoTopLine: 'Slate Solar and Storage',
    twoHeadline: 'xxMW Solar | xxMWH Storage',
    twoDescription: "",
    twoImg: require('../../images/ProjectImages/BrianJSEdited7.169.jpg').default,
    twoAlt: 'Slate',
    threeTopLine: 'Project Mustang',
    threeHeadline: 'xxMW Solar | xxMWH Storage',
    threeDescription: "",
    threeImg: require('../../images/ProjectImages/Wires1.169.jpg').default,
    threeAlt: 'Mustang',
    fourTopLine: 'Chevron Solar and Storage',
    fourHeadline: 'xxMW Solar | xxMWH Storage',
    fourDescription: "",
    fourImg: require('../../images/ProjectImages/BrianJSEdited6.169.jpg').default,
    fourAlt: 'Chevron',
    fiveTopLine: 'Marina Portfolio',
    fiveHeadline: 'xxMW Solar | xxMWH Storage',
    fiveDescription: "",
    fiveImg: require('../../images/ProjectImages/BrianJSEdited2.169.jpg').default,
    fiveAlt: 'Marina Portfolio',
    fiveLink: "https://www.energy-storage.news/news/goldman-sachs-renewable-power-buys-california-solar-plus-storage-plant",
    sixTopLine: 'SunPower Portfolio',
    sixHeadline: 'xxMW Solar | xxMWH Storage',
    sixDescription: "",
    sixImg: require('../../images/ProjectImages/BrianJSEdited4.169.jpg').default,
    sixAlt: 'Slate',
    sevenTopLine: 'Greenskies Portfolio',
    sevenHeadline: 'xxMW Solar | xxMWH Storage',
    sevenDescription: "",
    sevenImg: require('../../images/ProjectImages/BrianJSEdited.169.jpg').default,
    sevenAlt: 'Mustang',
    eightTopLine: 'TrueGreen Portfolio',
    eightHeadline: 'xxMW Solar | xxMWH Storage',
    eightDescription: "",
    eightImg: require('../../images/ProjectImages/BrianJSEdited8.169.jpg').default,
    eightAlt: 'Chevron',
};