
export const homeObj = {
  SectionOneid: "products",
  SectionOnelightBg: true,
  SectionOnelightText: true,
  SectionOneLightTextDesc: true,
  SectionOnetopLine: "Investment Services",
  SectionOneheadline:
    "Modeling, structuring and data management for projects at all stages",
  SectionOnedescription:
    "From NY to CA, development loans to tax equity, small C&I to Utility Scale we've seen it all and are equipped to expertly advise you through each transaction every step of the way.",
  SectionOnebuttonLabel: "Contact Us",
  SectionOnelistTitleOne: "Financial Structuring & Tax Equity",
  SectionOnelistOneObjectOne: "Fund Modeling",
  SectionOnelistOneObjectTwo: "Asset & Portfolio Modeling",
  SectionOnelistOneObjectThree: "Transaction Negotiation",
  SectionOnelistOneObjectFour: "Capital Markets Support",
  SectionOnelistOneObjectFive: "Investor Reporting",
  SectionOnelistTitleTwo: "Deal Diligence & Data Management",
  SectionOnelistTwoObjectOne: "Asset & Portfolio Diligence",
  SectionOnelistTwoObjectTwo: "Project Data Management",
  SectionOnelistTwoObjectThree: "Regulatory Compliance",
  SectionOnelistTwoObjectFour: "Legal & Contract Review",
  SectionOnelistTwoObjectFive: "Full Technical Stack Diligence",
  SectionOneimgStart: false,
  SectionOneimg: require("../../images/undraw/undraw_predictive_analytics_green.svg")
    .default,
  SectionOnealt: "",
  SectionOnedark: true,
  SectionOneprimary: true,
  SectionOnedarkText: false,
  SectionOnefadeTitleLeft: true,
  SectionOnefadeTitleRight: false,
  SectionOnefadeContentLeft: false,
  SectionOnefadeContentRight: true,
  SectionTwoid: "products2",
  SectionTwolightBg: false,
  SectionTwolightText: false,
  SectionTwoLightTextDesc: false,
  SectionTwotopLine: "Energy Storage",
  SectionTwoheadline:
    "Industry-leading energy storage modeling, risk management, and execution",
  SectionTwodescription:
    "Get access to our exclusive energy storage revenue, CapEx build-out, OpEx forecasting, and execution tools.",
  SectionTwobuttonLabel: "Contact Us",
  SectionTwolistTitleOne: "Technology Diligence",
  SectionTwolistOneObjectOne: "Revenue Analysis",
  SectionTwolistOneObjectTwo: "CapEx & OpEx Cost Modeling",
  SectionTwolistOneObjectThree: "Vendor & Technology Evaluation",
  SectionTwolistOneObjectFour: "EPC, LTSA, MSA Negotiation",
  SectionTwolistOneObjectFive: "Insurance Budgeting",
  SectionTwolistTitleTwo: "Engineering & Execution",
  SectionTwolistTwoObjectOne: "System Design",
  SectionTwolistTwoObjectTwo: "Energy Modeling",
  SectionTwolistTwoObjectThree: "IE Coordination",
  SectionTwolistTwoObjectFour: "Onsite Construction Modeling",
  SectionTwolistTwoObjectFive: "Augmentation Optimization",
  SectionTwoimgStart: true,
  SectionTwoimg: require("../../images/undraw/undraw_wind_turbine_green.svg")
    .default,
  SectionTwoalt: "",
  SectionTwodark: false,
  SectionTwoprimary: false,
  SectionTwodarkText: true,
  SectionTwofadeTitleLeft: false,
  SectionTwofadeTitleRight: true,
  SectionTwofadeContentLeft: true,
  SectionTwofadeContentRight: false,
  SectionThreeid: "products3",
  SectionThreelightBg: true,
  SectionThreelightText: false,
  SectionThreeLightTextDesc: false,
  SectionThreetopLine: "Execution Services",
  SectionThreeheadline: "On time, on budget, and built right",
  SectionThreedescription:
    "Our proven project execution excellence, technical acumen, planning & operational expertise build advantage at every project stage. Let us provide execution certainty through the construction phase of your assets with long-term asset operation at the forefront of our approach.",
  SectionThreebuttonLabel: "Contact Us",
  SectionThreelistTitleOne: "Execution Management",
  SectionThreelistOneObjectOne: "Owner's Engineering & Rep",
  SectionThreelistOneObjectTwo: "Contract & Change Management",
  SectionThreelistOneObjectThree: "Supply Chain Coordination",
  SectionThreelistOneObjectFour: "Quality Control & Assurance",
  SectionThreelistOneObjectFive: "Commissioning Coordination",
  SectionThreelistTitleTwo: "Pre-Construction Services",
  SectionThreelistTwoObjectOne: "Design & Equipment Selection",
  SectionThreelistTwoObjectTwo: "RFP Administration & Analysis",
  SectionThreelistTwoObjectThree: "Structural / Electrical Oversight",
  SectionThreelistTwoObjectFour: "Utility and IX Management",
  SectionThreelistTwoObjectFive: "I.E. Coordination & Management",
  SectionThreeimgStart: false,
  SectionThreeimg: require("../../images/undraw/undraw_QA_engineers_green.svg")
    .default,
  SectionThreealt: "",
  SectionThreedark: false,
  SectionThreeprimary: false,
  SectionThreedarkText: true,
  SectionThreefadeTitleLeft: true,
  SectionThreefadeTitleRight: false,
  SectionThreefadeContentLeft: false,
  SectionThreefadeContentRight: true,
  SectionFourid: "products4",
  SectionFourlightBg: false,
  SectionFourlightText: false,
  SectionFourLightTextDesc: false,
  SectionFourtopLine: "Development & Diligence Services",
  SectionFourheadline: "Project feasibility, siting, and underwrite certainty: let us guide the way",
  SectionFourdescription:
    "Whether you're developing a 500kW rooftop or a 300MW solar-plus-storage system, we leverage our deep expertise to ensure project development success with comprehensive risk identification & mitigation.",
  SectionFourbuttonLabel: "Contact Us",
  SectionFourlistTitleOne: "Feasibility Assessment",
  SectionFourlistOneObjectOne: "Site Characterization Analysis",
  SectionFourlistOneObjectTwo: "Market & Incentive Analysis",
  SectionFourlistOneObjectThree: "Offtake Economic Review",
  SectionFourlistOneObjectFour: "Energy Yield Assessments ",
  SectionFourlistOneObjectFive: "Preliminary Design Evaluation",
  SectionFourlistTitleTwo: "Full-Stack Development Support ",
  SectionFourlistTwoObjectOne: "Transaction Structuring",
  SectionFourlistTwoObjectTwo: "Agreement Negotiation",
  SectionFourlistTwoObjectThree: "Land Acquisition Support",
  SectionFourlistTwoObjectFour: "Comprehensive Risk Mitigation ",
  SectionFourlistTwoObjectFive: "Interconnection Support",
  SectionFourimgStart: true,
  SectionFourimg: require("../../images/undraw/undraw_circles_green.svg")
    .default,
  SectionFouralt: "",
  SectionFourdark: false,
  SectionFourprimary: false,
  SectionFourdarkText: true,
  SectionFourfadeTitleLeft: false,
  SectionFourfadeTitleRight: true,
  SectionFourfadeContentLeft: true,
  SectionFourfadeContentRight: false,
  SectionFiveid: "products5",
  SectionFivelightBg: true,
  SectionFivelightText: false,
  SectionFiveLightTextDesc: false,
  SectionFivetopLine: "Asset Management",
  SectionFiveheadline: "With Euclid, Asset Management isn't an after-thought",
  SectionFivedescription:
    "Euclid’s multidisciplinary data-driven approach makes it possible to scale our service offering to comprehensive asset management. We treat every single asset as if we owned it.",
  SectionFivebuttonLabel: "Contact Us",
  SectionFivelistTitleOne: "Operations Support",
  SectionFivelistOneObjectOne: "OpEx Planning & Analysis",
  SectionFivelistOneObjectTwo: "Revenue Optimization",
  SectionFivelistOneObjectThree: "Data Management & Cleansing",
  SectionFivelistOneObjectFour: "O&M Agreement Negotiation",
  SectionFivelistOneObjectFive: "Warranty Review & Remedy",
  SectionFivelistTitleTwo: "Stakeholder Management",
  SectionFivelistTwoObjectOne: "Powerful Reporting Tools",
  SectionFivelistTwoObjectTwo: "Incident & Outage Management",
  SectionFivelistTwoObjectThree: "Storage Retrofit Planning",
  SectionFivelistTwoObjectFour: "Billing & Collections",
  SectionFivelistTwoObjectFive: "Customer Contract Negotiation",
  SectionFiveimgStart: false,
  SectionFiveimg: require("../../images/undraw/undraw_financial_data_green.svg")
    .default,
  SectionFivealt: "",
  SectionFivedark: false,
  SectionFiveprimary: false,
  SectionFivedarkText: true,
  SectionFivefadeTitleLeft: true,
  SectionFivefadeTitleRight: false,
  SectionFivefadeContentLeft: false,
  SectionFivefadeContentRight: true,
};